global:
  resolve_timeout: 5m
  smtp_hello: smtp
  smtp_require_tls: false

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifier'

receivers:
  - name: 'email-notifier'
    email_configs:
      - to: 'rtheekshanafernando@gmail.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp:25'