groups:
- name: alerts
  rules:
  - alert: test-alert
    expr: test_gauge_with_random_values > 0.5
    for: 2s
    labels:
      severity: low
    annotations:
      summary: High request latency
- name: recorded-rule
  rules:
  - record: code:test_gauge_with_random_values:sum
    expr: test_gauge_with_random_values